name: Build, Run, Verify, Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
    SERVICE: 'exercise'
    saccount: ${{secrets.GCP_SERVICE_ACCOUNT}}
    PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag exercise:latest
        docker run -p 80:80 -d exercise:latest
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Configure docker for GCP'
      run: gcloud auth configure-docker
     
    - name: 'Build docker image'
      run:  docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/exercise:latest .
    - name: 'Push to Google Container Registry'
      run:  docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/exercise:latest 
    - name: 'Use gcloud CLI'
      run: |-
        gcloud run deploy $SERVICE \
          --region us-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/exercise:latest \
          --platform managed \
          --service-account=$saccount \
