name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
    SERVICE: 'exercise'
    saccount: ${{secrets.GCP_SERVICE_ACCOUNT}}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag exercise:latest
        docker run -p 80:80 -d exercise:latest
        
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
      
    - name: Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/exercise:latest
